### ISSUE TITLE
Need to save blob data in form instead of sending via ajax

### ISSUE THREAD

**Issue by myselfgaurav** [subins2000/Francium-voice#1]
hi is there way to save blob data in from ,

see what i am doing i have big form that works via post , so i add recorder there , now i want recorder file to be submitted via that form , not seprately from ajax. Is there way to add whole file to current form file input via js and then submit form .

I am using php

**Comment by subins2000** [comment]
You should use `FormData()` : http://stackoverflow.com/a/25647439/1372424
